### ISSUE TITLE
Support targeting repo directories

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [mapbox/stork#40]
Does Stork allow for targeting subdirectories with their own `package.json` for zipping?

# Use Case
I have a repo that is using step functions to create and monitor the progress of ecs-watchbot jobs. the repo has a single package.json which includes the dependencies for both the lambda step functions and the ecs-watchbot worker. Unfortunately the ecs-watchbot worker has dependencies that have build steps that depend on system libs that are not on the stork images. 

# Current work arounds
Using a custom stork image or moving the install of culprit dependencies into the ecs-watchbot Dockerfile. I would love to be able to have stork use an image representative of the lambda runtime, keep all my dependencies in a package.json and not have stork zip any dependencies not used by my lambda functions.

# Proposed change
If I could keep all of my lambda functions in their own directory with its own package.json and have stork target that directory I could avoid having to do any workaround nasty-jams and keep any ecs-watchbot only node_modules out of the lambda .zips

**Comment by jakepruitt** [comment]
@Ramshackle-Jamathon what would the pain level be to move the lambda functions into their own repository that's separate from the ecs-watchbot repository? As it stands now, the mapping of "One Repo <=> One Lambda Bundle" is pretty engrained into the stork model, which may make it difficult to modify the assumption that the repo has one lambda function and that lambda function is defined by the root package.json.

Since the convention of "one repo to one lambda bundle with the root package.json" is so common, I don't know if it makes sense to allow a `.stork.json` option for `package: lambda-funcs/package.json` would make sense for more than just this use case. 🤔 

As a workaround for your workflow, could it make sense to write a custom `buildspec.yml` that specifies the desired folder? (refs https://github.com/mapbox/stork#buildspecyml)

**Comment by Ramshackle-Jamathon** [comment]
@jakepruitt since the ecs-watchbot and step functions are pretty tightly coupled, splitting them out into their own repos would make deployments more painful. 

The custom `buildspec.yml` seems like an ideal workaround! Defining a lambda directory might only be something that nav-data might finds useful (we are working on a few repos that are using step-functions to maintain/react-to the state of an ecs-watchbot). I think it would be pretty nice to have a single location that maintains most of the stork buildspecs but I don't have a ton of insight on what other teams are jammin on.

**Comment by Ramshackle-Jamathon** [comment]
closing this. Using a custom `buildspec.yml` provides all the functionality required to do any subdirectory target jams. Super neat
